version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=real
    image: api.econrich.com:latest
    ports:
      - "3001:8080"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
